@startuml
[*] --> Stranger
Stranger --> Guest : authenticationFail
Stranger --> Member : authenticationSuccess \n t:username[string]
Stranger : o:isStranger[bool]

Guest --> LoggingIn : loginRequest
Guest : i:isMember[bool]

Member --> Guest : logout
Member : i:isMember[bool]

LoggingIn --> Guest : loginFail
LoggingIn --> Member : loginSuccess
@enduml